repos:
  - repo: local
    hooks:
      - id: biome-check
        name: Biome check
        entry: bun run check
        language: system
        pass_filenames: false
      - id: vitest
        name: Vitest
        entry: bun run test
        language: system
        pass_filenames: false
